### ISSUE TITLE
Cannot start slag on Windows 10 Bash

### ISSUE THREAD

**Issue by gimmebytes** [thehandsomepanther/slag#31]
Hi there,

thanks for creating this nice little piece of software. 

I tried to install slag on Windows 10 Bash (Ubuntu on Windows 10) - installing node and npm went fine, but when starting slag the following message comes up:

```
TypeError: Cannot read property 'channel' of undefined
    at slack.channels.info (/usr/local/lib/node_modules/slag-cli/util/getChannels.js:47:24)
    at _res (/usr/local/lib/node_modules/slag-cli/node_modules/slack/methods/_exec.js:37:7)
    at IncomingMessage.__end (/usr/local/lib/node_modules/slag-cli/node_modules/tiny-json-http/_write.js:69:9)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Any ideas on how to fix this?

Cheers

**Comment by vegarab** [comment]
Have you set a channel/team? 
Can be done like this when setting token: 
```
slag --add-token <your-token> --team <team-name>
```
or check your json file's structure if you set it directly there.
